%% Constantes das substâncias:
MMa = 50e-3;                    %kg/mol
MMb = 50e-3;                    %kg/mol
MMc = 50e-3;                    %kg/mol
MMd = 50e-3;                    %kg/mol
MMm = 18e-3;                    %kg/mol
pm = 1;                         %kg/L
pf = 1;                         %kg/L
Cpm = 4186/(18e-3);             %J/kg.K
Cpf = 4186/(18e-3);             %J/kg.K

%% Constantes da reação (aA + bB -> cC + dD):
a = 1;                          %
b = 2;                          %
c = 1;                          %
d = 2;                          %
Cao = 10;                       %mol/L
Cbo = 20;                       %mol/L
Cco = 0;                        %mol/L
Cdo = 0;                        %mol/L
ko = 0.001;                     %s^-1*(L/mol)^(a+b-1)
Ea = 5000;                      %J/mol
R = 8.314;                      %J/mol.K
dHr = -200000;                  %J/mol

%% Constantes do reator:
Vo = 1;                         %L
D = 5;                          %dm
H = 15;                         %dm
A = (pi*D^2)/4;                 %dm2
Vmax = A*H;                     %L
Vc = Vmax/10;                   %L
Qo = 1;                         %L/s
Qco = 0.2;                      %L/s
kv = 1;                         %L/s
rho = 1;                        %kg/L
To = 298;                       %K
Tco = 290;                      %K
U = 2000;                       %W/dm2.K
